//
// Created by ganymed on 30/03/16.
//

#ifndef PINMAPPINGS_H
#define PINMAPPINGS_H

#include <avr/io.h>


/*      Shift Register      */

#define SHIFT_REGISTER_DATA_OUT_PIN PINB2
#define SHIFT_REGISTER_DATA_OUT_PORT PORTB
#define SHIFT_REGISTER_DATA_OUT_DDR DDRB
#define SHIFT_REGISTER_DATA_OUT_DDR_PIN DDB2

#define SHIFT_REGISTER_SHIFT_CLOCK_PIN PINB1
#define SHIFT_REGISTER_SHIFT_CLOCK_PORT PORTB
#define SHIFT_REGISTER_SHIFT_CLOCK_DDR DDRB
#define SHIFT_REGISTER_SHIFT_CLOCK_DDR_PIN DDB1

#define SHIFT_REGISTER_STORAGE_CLOCK_PIN PINB0
#define SHIFT_REGISTER_STORAGE_CLOCK_PORT PORTB
#define SHIFT_REGISTER_STORAGE_CLOCK_DDR DDRB
#define SHIFT_REGISTER_STORAGE_CLOCK_DDR_PIN DDB0


/*      7 Segment       */

#define LED_A_PIN PIND2
#define LED_A_PORT PORTD
#define LED_A_DDR DDRD
#define LED_A_DDR_PIN DDD2

#define LED_B_PIN PIND3
#define LED_B_PORT PORTD
#define LED_B_DDR DDRD
#define LED_B_DDR_PIN DDD3

#define LED_C_PIN PIND4
#define LED_C_PORT PORTD
#define LED_C_DDR DDRD
#define LED_C_DDR_PIN DDD4

#define LED_D_PIN PIND5
#define LED_D_PORT PORTD
#define LED_D_DDR DDRD
#define LED_D_DDR_PIN DDD5

#define LED_E_PIN PIND6
#define LED_E_PORT PORTD
#define LED_E_DDR DDRD
#define LED_E_DDR_PIN DDD6

#define LED_F_PIN PIND7
#define LED_F_PORT PORTD
#define LED_F_DDR DDRD
#define LED_F_DDR_PIN DDD7

#define LED_G_PIN PINB0
#define LED_G_PORT PORTB
#define LED_G_DDR DDRB
#define LED_G_DDR_PIN DDB0


/*       DIP Switch      */

#define DIP_SWITCH_1_PIN PINB3
#define DIP_SWITCH_1_PIN_REGISTER PINB
#define DIP_SWITCH_1_PORT PORTB
#define DIP_SWITCH_1_DDR DDRB
#define DIP_SWITCH_1_DDR_PIN DDB3

#define DIP_SWITCH_2_PIN PINB4
#define DIP_SWITCH_2_PIN_REGISTER PINB
#define DIP_SWITCH_2_PORT PORTB
#define DIP_SWITCH_2_DDR DDRB
#define DIP_SWITCH_2_DDR_PIN DDB4

#define DIP_SWITCH_3_PIN PINB5
#define DIP_SWITCH_3_PIN_REGISTER PINB
#define DIP_SWITCH_3_PORT PORTB
#define DIP_SWITCH_3_DDR DDRB
#define DIP_SWITCH_3_DDR_PIN DDB5


#endif //HEIMPROJEKT02_PINMAPPINGS_H
